In [3]:
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]])
print("Dimension of a :", a.ndim,"\nSize of a :",a.shape,'\nType of a :',a.dtype)

Dimension of a : 2 
Size of a : (2, 3) 
Type of a : int32


In [10]:
a = np.array([[1, 2, 3],[4, 5, 6]],dtype = np.float32)
print("Dimension of a :", a.ndim,"\nSize of a :",a.shape,'\nType of a :',a.dtype)

Dimension of a : 2 
Size of a : (2, 3) 
Type of a : float32


In [18]:
b = np.ones([3,4])
c = np.zeros([2,2])
d = np.identity(4,dtype = np.int32)
print('Matrix ones :\n',b)
print('Matrix zeros :\n',c)
print('Matrix identity :\n',d)

Matrix ones :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matrix zeros :
 [[0. 0.]
 [0. 0.]]
Matrix identity :
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [22]:
#ค่าเริ่มต้น ค่าสุดท้าย การเพิ่มขึ้น
e = np.arange(1,80,2)
print("np.arange\n",e)
#ค่าเริ่มต้น ค่าสุดท้าย จำนวนค่าในช่วง
f = np.linspace(1,80,50)
print("np.linspace\n",f)

np.arange
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79]
np.linspace
 [ 1.          2.6122449   4.2244898   5.83673469  7.44897959  9.06122449
 10.67346939 12.28571429 13.89795918 15.51020408 17.12244898 18.73469388
 20.34693878 21.95918367 23.57142857 25.18367347 26.79591837 28.40816327
 30.02040816 31.63265306 33.24489796 34.85714286 36.46938776 38.08163265
 39.69387755 41.30612245 42.91836735 44.53061224 46.14285714 47.75510204
 49.36734694 50.97959184 52.59183673 54.20408163 55.81632653 57.42857143
 59.04081633 60.65306122 62.26530612 63.87755102 65.48979592 67.10204082
 68.71428571 70.32653061 71.93877551 73.55102041 75.16326531 76.7755102
 78.3877551  80.        ]


In [34]:
#เพิ่มอถวเข้าไปต่อท้าย โดยหลักต้องเท่ากัน
A1 = np.ones([3,2])
A2 = np.zeros([4,2])
B = np.concatenate([A1,A2])
print("np.concatenate\n",B)
#เพิ่มหลักเข้าไปต่อท้าย โดยแถวต้องเท่ากัน
A1 = np.ones([4,3])
A2 = np.zeros([4,5])
B = np.concatenate([A2,A1], axis = 1)
print("np.concatenate\n",B)
#เปลี่ยนชนิดของ Matrix B
C= B.astype(np.int32)
print("C= B.astype(np.int32)\n",C)

np.concatenate
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
np.concatenate
 [[0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1.]]
C= B.astype(np.int32)
 [[0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1 1]]


In [44]:
#copy ขนาดของ Matrixเพิ่มสร้าง 0 หรือ 1
B1 = np.array([[1,2,3],[4,5,6]],dtype = np.int32)
print("No Change\n",B1)
B2 = np.zeros_like(B1)
B3 = np.ones_like(B1)
print("np.zeros_like(B1)\n",B2)
print("np.ones_like(B1)\n",B3)

#matrix ที่บอกขนาดแล้วจะ random ค่าออกมาให้โดยมีค่าตั้งแต่ 0-1
C1 = np.random.random([4,5])
C2 = C1.astype(np.int32)
print("random\n",C1)
print("Change Type to int\n",C2)

No Change
 [[1 2 3]
 [4 5 6]]
np.zeros_like(B1)
 [[0 0 0]
 [0 0 0]]
np.ones_like(B1)
 [[1 1 1]
 [1 1 1]]
random
 [[0.39323252 0.36685139 0.22275623 0.15240118 0.09881666]
 [0.23936484 0.20948727 0.64390473 0.9975305  0.68443308]
 [0.09303028 0.4910897  0.84106083 0.2500643  0.7054809 ]
 [0.51528305 0.48493205 0.67100394 0.85363984 0.29047235]]
Change Type to int
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [73]:
#สร้าง Array ขึ้นมา
D1 = np.linspace(1,6,6, dtype = np.int32)
print("random\n",D1)
#เช็คว่ามีกี่ Array
D11 = D1.size 
D12 = D1.mean()
D13 = D1.max()
D14 = D1.min()
print("Sixe of D1\n",D11)
print("Mean of D1\n",D12)
print("Max of D1\n",D13)
print("Min of D1\n",D14)
#การ reshape จะต้องมีขนาดของมิติเท่ากับจำนวน Array
D2 = D1.reshape(2,3)
print("reshape D2\n",D2)
#การใส่ -1 ไว้ตรง แถว หรือ หลัก หมายความว่า จัดมาให้เลยเท่าไหร่ก็ได้ของให้ได้ตามจำนวน แถว หรือ หลักที่เรากำหนด
D3 = D1.reshape(2,-1)
print("reshape D3\n",D3)
#ของแค่ 1 แถว 
D4 = D1.ravel()
print("revel D4\n",D4)

random
 [1 2 3 4 5 6]
Sixe of D1
 6
Mean of D1
 3.5
Max of D1
 6
Min of D1
 1
reshape D2
 [[1 2 3]
 [4 5 6]]
reshape D3
 [[1 2 3]
 [4 5 6]]
revel D4
 [1 2 3 4 5 6]


In [80]:
E1 = np.arange(10)
print(E1)
#แปลงเป็น 5 แถว 2 หลัก
E1 = E1.reshape(5,2)
print(E1)
#หรือจะเขียน . กันเลยก็จะให้ค่าสุดท้ายเหมือนกัน E1 = np.arange(10).reshape(5,2)

#การทำ Transpose หรือขจะใช้ E1 = E1.transpose([1,0]) 
E1 = E1.T 

print(E1)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [91]:
#Arithematic Operators
a = np.arange(5,11)
print(a)
b = np.linspace(1,6,6, dtype = np.int32)
print(b)
c= b+a
print(c)
#Logical operator
c = c > 8 
print(c)
#in place operation modify
a *= b
print(a)

[ 5  6  7  8  9 10]
[1 2 3 4 5 6]
[ 6  8 10 12 14 16]
[False False  True  True  True  True]
[ 5 12 21 32 45 60]


In [96]:
a = np.arange(2,10)
print(a)
a = pow(a,2)
print(a)
a = np.sqrt(a)
a = a.astype(np.int32)
print(a)

[2 3 4 5 6 7 8 9]
[ 4  9 16 25 36 49 64 81]
[2 3 4 5 6 7 8 9]


In [33]:
#Indexing 1.1
i=0;j=6
a0 = np.arange(0,6)
a1 = np.arange(10,16)
a2 = np.arange(20,26)
a3 = np.arange(30,36)
a4 = np.arange(40,46)
a5= np.arange(50,56)
a = np.concatenate([a0,a1,a2,a3,a4,a5]).reshape(6,6)
print(a)
b1 = a[4:,4:]
b2 = a[0,3:5]
b3 = a[:,2]
b4 = a[2::2,::2]
print("\n",b1)
print("\n",b2)
print("\n",b3)
print("\n",b4)


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

 [[44 45]
 [54 55]]

 [3 4]

 [ 2 12 22 32 42 52]

 [[20 22 24]
 [40 42 44]]


In [111]:
#Indexing 1.2
i=0
sum = 0
a = []
for i in range(0,6):
    for j in range(0,6):
        a.append(i*10+j)
        d = (i*10+j)
        sum +=d
a = np.array([a]).reshape(6,6) 
print(a)
print(a[1::2,::2])
print("Sum :",sum)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[10 12 14]
 [30 32 34]
 [50 52 54]]
Sum : 990


In [126]:
#Sum of Array
r1= a.sum()
r2= a.sum(axis=0)
r3= a.sum(axis=1)
r4= a.sum(axis=0,keepdims=True)
r5= a.sum(axis=1,keepdims=True)
r6= a.sum(axis=1,keepdims=False)
r7= a.sum(axis=0,keepdims=False)
print("sum of all element :",r1)
print("sum of .sum(axis=0) :",r2)
print("sum of .sum(axis=1) :",r3)
print("sum of .sum(axis=0,keepdims=True) :",r4)
print("sum of .sum(axis=1,keepdims=True) :\n",r5)
print("sum of .sum(axis=1,keepdims=False) :\n",r6)
print("sum of .sum(axis=0,keepdims=False) :\n",r7)

sum of all element : 990
sum of .sum(axis=0) : [150 156 162 168 174 180]
sum of .sum(axis=1) : [ 15  75 135 195 255 315]
sum of .sum(axis=0,keepdims=True) : [[150 156 162 168 174 180]]
sum of .sum(axis=1,keepdims=True) :
 [[ 15]
 [ 75]
 [135]
 [195]
 [255]
 [315]]
sum of .sum(axis=1,keepdims=False) :
 [ 15  75 135 195 255 315]
sum of .sum(axis=0,keepdims=False) :
 [150 156 162 168 174 180]


In [138]:
#Broard Cast
#3*2
Matrix1 = np.array([[1, 2],[3, 4],[5, 6]])
print(Matrix1)
#1*2
Matrix2 = np.array([[1,-1]])
print(Matrix2)

#หมาเหตุถ้าจะบวกการทุกสมาชิกแบบนี้จะต้อง มีจำนวนหลักเท่ากัน
Matrix1 + Matrix2

[[1 2]
 [3 4]
 [5 6]]
[[ 1 -1]]


array([[2, 1],
       [4, 3],
       [6, 5]])

In [164]:
import math 
x1 = np.exp(1)
x2 = np.sqrt(2)
x3 = np.sin(math.pi/6)
x4 = np.isnan(3)
print(x1,x2,x3,x4,end="")

2.718281828459045 1.4142135623730951 0.49999999999999994 False

In [165]:
pow(2,3)

8

In [173]:
from numpy.linalg import inv
mat = np.array([[1,2],[4,5]])
print(mat)
print(inv(mat))
print(np.dot(mat,inv(mat)))


[[1 2]
 [4 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[1. 0.]
 [0. 1.]]


In [180]:
Xb = np.array([[2,4],[4,6]])
print(Xb)
Y = np.array([2,3])
print(Y)
W = np.linalg.solve(Xb.T*Xb,Xb.T*Y)
print(W)

[[2 4]
 [4 6]]
[2 3]
[[-0.14285714 -1.28571429]
 [ 0.28571429  1.07142857]]
