In [2]:
import pandas as pd

df = pd.read_csv("E:/SUT Subject/Artificial Intelligence 3.62 2019/SalaryData.csv")
df

z     x     x^2       y
0   1   1.1    1.21   39343
1   1   1.3    1.69   46205
2   1   1.5    2.25   37731
3   1   2.0    4.00   43525
4   1   2.2    4.84   39891
5   1   2.9    8.41   56642
6   1   3.0    9.00   60150
7   1   3.2   10.24   54445
8   1   3.2   10.24   64445
9   1   3.7   13.69   57189
10  1   3.9   15.21   63218
11  1   4.0   16.00   55794
12  1   4.0   16.00   56957
13  1   4.1   16.81   57081
14  1   4.5   20.25   61111
15  1   4.9   24.01   67938
16  1   5.1   26.01   66029
17  1   5.3   28.09   83088
18  1   5.9   34.81   81363
19  1   6.0   36.00   93940
20  1   6.8   46.24   91738
21  1   7.1   50.41   98273
22  1   7.9   62.41  101302
23  1   8.2   67.24  113812
24  1   8.7   75.69  109431
25  1   9.0   81.00  105582
26  1   9.5   90.25  116969
27  1   9.6   92.16  112635
28  1  10.3  106.09  122391
29  1  10.5  110.25  121872

In [157]:
import numpy as np
from numpy.linalg import inv
Matrix = df.values
M1 = Matrix[0:3,0].reshape(-1,1)
M2 = Matrix[0:3,1].reshape(-1,1)
M3 = Matrix[0:3,2].reshape(-1,1)
M4  = Matrix[0:3,3].reshape(-1,1)
Y = M4
MS = np.concatenate([M1,M2,M3], axis = 1)
InvMS = inv(MS)
#W = np.linalg.solve(MS.T*MS,MS.T*Y)
print(Y)
print(InvMS)
def Matrix_R(InvMS,Y):
#fine result of matrix
    Sum = 0
    ans = []
    for i in range(len(InvMS)):
        for j in range(len(Y)):
            Sum += InvMS[i,j]*Y[j,0]
        ans.append([Sum])
        Sum = 0 
    return np.array(ans)

a = inv(np.array([[1, -1, 1,2,1],[1,1,1,1,1],[1,3,9,9,10],[1,2,3,1,2],[4,5,6,1,2]]))
b = np.array([[-1],[1],[27],[1],[2]])

Matrix_R(InvMS,Y)#.astype(np.float32)
Matrix_R(a,b)#.astype(np.float32)

print(a)
a[:,0]

[[39343.]
 [46205.]
 [37731.]]
[[ 24.375 -41.25   17.875]
 [-35.     65.    -30.   ]
 [ 12.5   -25.     12.5  ]]
[[ 0.625       1.125      -0.375       1.45833333 -0.45833333]
 [-0.75        0.25        0.25       -1.41666667  0.41666667]
 [ 0.125      -1.375       0.125      -0.375       0.375     ]
 [-0.5        -0.5         0.5        -2.83333333  0.83333333]
 [ 0.5         1.5        -0.5         3.16666667 -1.16666667]]


array([ 0.625, -0.75 ,  0.125, -0.5  ,  0.5  ])

In [151]:
M1 = Matrix[:,1].reshape(-1,1)
M1
#W = np.linalg.solve(B.T*B,B.T*Y)

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])